-- ═══════════════════════════════════════════════════════════════════
-- QA CONTROL CENTER — Nuevos aplicativos del catálogo
-- Ejecutar en: Supabase → SQL Editor → Run
-- ON CONFLICT DO NOTHING: no toca los ya existentes
-- ═══════════════════════════════════════════════════════════════════

INSERT INTO aplicativos_catalogo (codigo, nombre, orden) VALUES
  ('APIENVIO',   'API-EnvíoCorreos',                         109),
  ('APIMULTI',   'API MultiServices',                        110),
  ('BIBLIO',     'Biblioteca',                               111),
  ('CCNX',       'Cadenas de Conexión',                      112),
  ('CALCPRI',    'Calculadora Pricing',                      113),
  ('CEEFF',      'Carga Estados Financieros',                114),
  ('CAVIFI',     'Cavifi',                                   115),
  ('CLNEG',      'Clínica de Negocios',                      116),
  ('COBMYPE',    'Cobmype',                                  117),
  ('ENCAJE',     'Encaje123',                                118),
  ('FEMP',       'Feria del Emprendedor',                    119),
  ('FICOBERT',   'Ficobert',                                 120),
  ('GCUMP',      'Gestión de Cumplimiento',                  121),
  ('GVOL',       'Gestores Voluntarios',                     122),
  ('INFOBLOOM',  'InfoBloomberg',                            123),
  ('INTRANET',   'Intranet',                                 124),
  ('LAVACT',     'Lavado de Activos',                        125),
  ('LBTR',       'LBTR',                                     126),
  ('LIBELE',     'Libros Electrónicos',                      127),
  ('MFID',       'Masivo Fideicomisos',                      128),
  ('MICROCR',    'Microcredito',                             129),
  ('MFPUNO',     'MicroFinanzasPuno',                        130),
  ('MICROGLO',   'Microglobal',                              131),
  ('MIGBD',      'Migración BD',                             132),
  ('MIGCR',      'Migración Cristal Reports',                133),
  ('MIGSCO',     'Migración SCO, EstEco, Ficobert',          134),
  ('PFE',        'PFE',                                      135),
  ('PGC19',      'PGC19',                                    136),
  ('PLANTA',     'Plantillas Automatizadas',                 137),
  ('PCNEG',      'Portal Conexión y Negocios',               138),
  ('PJUD',       'Procesos Judiciales',                      139),
  ('PWOG',       'Proyecto Web OG',                          140),
  ('REPO',       'Repo',                                     141),
  ('REPOADM',    'RepoAdmin',                                142),
  ('SAFCO',      'SAFCO',                                    143),
  ('SGH',        'Sistema Gestión Humana',                   144),
  ('SFTP',       'SFTP',                                     145),
  ('SFIN',       'Servicios Financieros',                    146),
  ('SGSCD',      'SGSCD',                                    147),
  ('SIAR',       'SIAR',                                     148),
  ('SIAT',       'SIAT',                                     149),
  ('SIJUS',      'SIJUS',                                    150),
  ('SPAMC',      'SPA&MC',                                   151),
  ('SWIFT',      'SWIFT',                                    152),
  ('TALLCAP',    'Talleres y Capacitaciones',                153),
  ('TESTLINK',   'TestLink',                                 154),
  ('TIMESYS',    'TIMESYS',                                  155),
  ('TIPOCAM',    'Tipo de Cambio',                           156),
  ('UPGSAP',     'Upgrade Sist. Operativo de SAP',           157),
  ('VALIDEITOR', 'Valideitor',                               158),
  ('WIN10',      'Windows 10',                               159),
  ('WINFOGEM',   'Winfogem',                                 160),
  ('WSGEN',      'WS-Genéricos',                             161),
  ('PRY-TEST',   'Servicio de Testing',                      162),
  ('ESTABWMV',   'Estabilización de WF Mivienda',            163),
  ('GGHA',       'GGHA',                                     164)
ON CONFLICT (codigo) DO NOTHING;
