-- ═══════════════════════════════════════════════════════════════════
-- QACC — Catálogo oficial de Aplicativos (Matriz Real del Cliente)
-- Ejecutar en: Supabase → SQL Editor → Run
-- ═══════════════════════════════════════════════════════════════════

-- UPSERT completo: actualiza nombre/color si ya existe, inserta si no.
-- NO elimina los que no están en la lista para no romper FK en requirements.

INSERT INTO aplicativos_catalogo (codigo, nombre, color, activo, orden) VALUES

-- ── APIs / Integraciones ────────────────────────────────────────────
('APGEN',        'Aplicaciones Genéricas',                               '#0EA5E9', true,   10),
('APIBW',        'API Servicios Workflow de Negocios',                   '#0EA5E9', true,   20),
('APIHONRAS',    'API Honras',                                           '#0EA5E9', true,   30),
('ARENIEC',      'API RENIEC',                                           '#0EA5E9', true,   40),
('APIMS',        'API Multiservicios SUNAT',                             '#0EA5E9', true,   50),
('SIAPIAD',      'API Directorio Activo',                                '#0EA5E9', true,   60),
('MAIL',         'API Correo',                                           '#0EA5E9', true,   70),
('SGAU',         'API SGAU',                                             '#0EA5E9', true,   80),

-- ── BI / Inteligencia de Negocios ───────────────────────────────────
('BI-CDE',       'BI-Reportes CDE',                                      '#3B82F6', true,  100),
('BI-DMRI',      'Datamart Riesgos',                                     '#3B82F6', true,  110),
('BI-FMV',       'BI-Calendarios Fondo Mi Vivienda',                     '#3B82F6', true,  120),
('BI-LCONTA',    'BI-Extracción Asientos Contables',                     '#3B82F6', true,  130),
('BI-OSCE',      'BI-Carga OSCE',                                        '#3B82F6', true,  140),
('BI-PLAT',      'Componentes Solución BI',                              '#3B82F6', true,  150),
('BI-PRIDER',    'Dashboard PRIDER',                                     '#3B82F6', true,  160),
('BI-SALEXP',    'BI-Saldo de Exposición GO',                            '#3B82F6', true,  170),
('BI-SIG',       'Sistema Información Gerencial',                        '#3B82F6', true,  180),
('BI-SRDL',      'Sistema de Registro de Datos en Línea (SRDL)',         '#3B82F6', true,  190),

-- ── Sistemas Corporativos / Sharepoint ──────────────────────────────
('CD',           'Site Centro de Documentos (Sharepoint)',               '#8B5CF6', true,  200),
('T-ASESORA',    'Site Consultas Legales (Sharepoint)',                  '#8B5CF6', true,  210),
('CVIVE',        'Intranet Vive Cofide (GOINTEGRO)',                     '#8B5CF6', true,  220),
('EXT.GGHH',     'Aplicación Externa Gestión Humana',                   '#8B5CF6', true,  230),
('TMATE',        'Solución TeamMate (UAI)',                              '#8B5CF6', true,  240),
('NDOC',         'Solución NetDocuments',                                '#8B5CF6', true,  250),

-- ── Sistemas Generales ──────────────────────────────────────────────
('GSERT',        'Gestión Servicio Aseguramiento Calidad',               '#64748B', true,  300),
('NFAC',         'No Facturable',                                        '#64748B', true,  310),
('PGC',          'Sistema del Programa de Garantías COVID',              '#64748B', true,  320),
('SBDP',         'Sistema Base de Datos Personal',                       '#64748B', true,  330),
('SC',           'Sistema Centralizado',                                 '#64748B', true,  340),
('SDR',          'Sistema de Denuncias',                                 '#64748B', true,  350),
('SEPYMEX_V2',   'Sistema SEPYMEX V2',                                   '#64748B', true,  360),
('SGC',          'Sistema de Gestión de Contratos',                      '#64748B', true,  370),
('SGP',          'Sistema de Gestión de Postulantes',                    '#64748B', true,  380),
('SIMP',         'Sistema Impulso MyPerú',                               '#64748B', true,  390),
('SISNOTIF',     'Sistema de Notificación',                              '#64748B', true,  400),
('SLDU',         'Sistema Libros Digitales Únicas',                      '#64748B', true,  410),
('SMP',          'Sistema Multiproducto',                                '#64748B', true,  420),
('SNT',          'Sistema de Intermediación / SINTER',                   '#64748B', true,  430),
('SPB',          'Sistema Proyecto Base',                                '#64748B', true,  440),
('STAT',         'Estadísticas Económicas',                              '#64748B', true,  450),
('STFTP',        'Sistema de Transferencia FTP a Banco',                 '#64748B', true,  460),
('VSOF',         'Sistema de Registro de Visitas de COFIDE (VISOF)',     '#64748B', true,  470),
('WMV',          'Workflow Mi Vivienda',                                 '#64748B', true,  480),

-- ── SAP Módulos ─────────────────────────────────────────────────────
('SAP-ACCPRE',   'Acciones Preferentes',                                 '#F59E0B', true,  500),
('SAP-AMAA',     'Amortización Activos Fijos',                           '#F59E0B', true,  510),
('SAP-AN08',     'Anexo 8',                                              '#F59E0B', true,  520),
('SAP-BONOI',    'Bonos de Inversiones',                                 '#F59E0B', true,  530),
('SAP-BP',       'Business Partner (BP)',                                '#F59E0B', true,  540),
('SAP-CFMV',     'Cobranza FMV',                                         '#F59E0B', true,  550),
('SAP-CLAFRI',   'Clasificación de Riesgos',                             '#F59E0B', true,  560),
('SAP-COCA',     'Contratos Calendarios',                                '#F59E0B', true,  570),
('SAP-COMP',     'Compensación de Asientos Contables',                   '#F59E0B', true,  580),
('SAP-CTTC',     'Contratos Traslado Tratamiento Contable',              '#F59E0B', true,  590),
('SAP-FFID',     'Facturación Fideicomisos (SD)',                        '#F59E0B', true,  600),
('SAP-FFIN',     'Facturación Finanzas (FI)',                            '#F59E0B', true,  610),
('SAP-GAR',      'Garantías',                                            '#F59E0B', true,  620),
('SAP-LIBELE',   'Libros Electrónicos',                                  '#F59E0B', true,  630),
('SAP-PCON',     'Plan Concluido',                                       '#F59E0B', true,  640),
('SAP-PED',      'Pedido de Logística',                                  '#F59E0B', true,  650),
('SAP-PPAR',     'Prepagos Parciales',                                   '#F59E0B', true,  660),
('SAP-PROV',     'Provisiones',                                          '#F59E0B', true,  670),
('SAP-RCD',      'Reporte Crediticio de Deudores (RCD)',                 '#F59E0B', true,  680),
('SAP-REFRESH',  'Actualización de SAP Productivo a QAS',                '#F59E0B', true,  690),
('SAP-REGFI',    'Registros Contables Finanzas',                         '#F59E0B', true,  700),
('SAP-REPCON',   'Reporte de Contratos SAP',                             '#F59E0B', true,  710),
('SAP-REPOS',    'REPOS',                                                '#F59E0B', true,  720),
('SAP-SOLPED',   'SOLPE',                                                '#F59E0B', true,  730),
('SAP-VME',      'Valoración Moneda Extranjera',                         '#F59E0B', true,  740),
('SAP-WFDAF',    'Workflow DAF',                                         '#F59E0B', true,  750),
('SAP-WIT',      'Workflow Integrado de Transferencia',                  '#F59E0B', true,  760),

-- ── Sistemas [NO SAP] ───────────────────────────────────────────────
('BFID',         'Sistema Búsqueda de Fideicomisos',                    '#10B981', true,  800),
('CDE',          'Sistema CDE',                                          '#10B981', true,  810),
('CCOFI',        'Customer Cofide (Compliance)',                         '#10B981', true,  820),
('CUMPLE',       'Sistema Cumpleaños',                                   '#10B981', true,  830),
('EEFF',         'Sistema de Carga SBS',                                 '#10B981', true,  840),
('FAE',          'Sistema de Fondo de Apoyo Empresarial',                '#10B981', true,  850),
('FCEI',         'Sistema FCEI',                                         '#10B981', true,  860),
('FIFPPA',       'Sistema FIFPPA',                                       '#10B981', true,  870),
('FIRMAS',       'Sistema Firmas',                                       '#10B981', true,  880),
('FOGEM',        'Sistema FOGEM',                                        '#10B981', true,  890),
('INFOG',        'Sistemas INFOGAS',                                     '#10B981', true,  900),
('MEEFF',        'Sistema de Metodización',                              '#10B981', true,  910),
('MYF',          'App Mi Yunta Financiero',                              '#10B981', true,  920),
('PAE',          'Sistema de Programa de Apoyo Empresarial',             '#10B981', true,  930),
('PGCC',         'PGCC',                                                 '#10B981', true,  940),
('PORTALCOFIDE', 'Sistema Portal COFIDE',                                '#10B981', true,  950),
('PRICING',      'Sistema Pricing',                                      '#10B981', true,  960),
('RCC',          'Sistema RCC',                                          '#10B981', true,  970),
('RCD',          'Reporte Crediticio de Deudores',                       '#10B981', true,  980),
('RFA',          'Sistema RFA',                                          '#10B981', true,  990),
('SCAP',         'Sistema de Capacitación al Agricultor RFA',            '#10B981', true, 1000),
('SCP',          'Sistema de Cadenas Productivas',                       '#10B981', true, 1010),
('SCM',          'Sistema de Carga Masiva de Crédito',                   '#10B981', true, 1020),
('SCO',          'Sistema de Contratos',                                 '#10B981', true, 1030),
('SEPYMEX',      'Sistema SEPYMEX',                                      '#10B981', true, 1040),
('SFC',          'Sistema de Fondo Crecer',                              '#10B981', true, 1050),
('SGD',          'Sistema de Gestión Documental',                        '#10B981', true, 1060),
('SGCC',         'Sistema SGCC',                                         '#10B981', true, 1070),
('SIGCNOR',      'Sistema de Gestión y Control Normativo',               '#10B981', true, 1080),
('SIGOBL',       'Sistema de Gestión de Obligaciones',                   '#10B981', true, 1090),
('SIGORG',       'Sistema de Gestión de Órdenes de Giro',                '#10B981', true, 1100),
('SPLAFT',       'SPLAFT',                                               '#10B981', true, 1110),
('SRP',          'Sistema Reactiva Perú',                                '#10B981', true, 1120),
('STD',          'Sistema de Trámite Documentario (Antiguo)',            '#10B981', true, 1130),
('SUC',          'Sistema de Usuarios Centralizados',                    '#10B981', true, 1140),
('TCREUTERS',    'Sistema TcReuters',                                    '#10B981', true, 1150),
('UNE',          'Sistema de Unidad de Emprendimiento',                  '#10B981', true, 1160),
('OTROS',        'Otros',                                                '#94A3B8', true, 9999)

ON CONFLICT (codigo) DO UPDATE SET
  nombre = EXCLUDED.nombre,
  color  = EXCLUDED.color,
  orden  = EXCLUDED.orden,
  activo = true;
